---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReeaWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: proxy
    author: jeevan
spec:
  containers:
    - name: mynginx
      image: nginx
      volumeMounts:
        - name: my-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
...
-> kubectl get pv
-> kubectl get pvc
-> kubectl get pods
-> kubectl exec -it nginx-pod -- bash
-> cd /usr/share/nginx/html 
   C&P any html code from google in folder = cat > index.html
  -> kill 1
-> kubectl exec -it nginx-pod -- bash
-> cat index.html

