secrets: we can expose thr database deployment file but in the secret definition file we just remove the read permissiosn on that file
using chmod so that other people cant see the content. we just hiding the data so that people who has acess for the deployment definition files 
they dont know what is the secret crredentials the secret files are npot given the read permissions and they are located in a seperate location 
using chmod removing permissions for group and other 
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret         (this file linked with redis-deployment file)
type: Opaque
stringData:
  a: amVldmFua29obGkgdXNlcgo=
...
-> ls -l
-> chmod 700 -R secret.yaml
we can also add another level of security by encripitting the data if someone accidently opens no one can remember that
-> echo "jeevan" | base64 = amVldmFua29obGkgdXNlcgo=
-> kubectl apply -f secret.yaml
-> kubectl apply -f redis-deployment.yaml
-> kubectl exec -it redis-deployment --bash
--------------------------------------------------------------------------------------------------------------------------------------------
example 2
vim postges-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
stringData:
    username: bXl1c2VyIHVzZXIK
    password: amVldmFua29obGkgdXNlcgo=
    dbname: bXlkYiB1c2VyCg==
...

vim postgres-deployemnt.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-app-deployment
    labels:
      name: postgres-app
      author: jeevan
spec:
    replicas: 2
    selector:
      matchLabels:
        type: postgres-app
    template:
      metadata:
        name: postgres-app-pod
        labels:
          type: postgres-app
      spec:
        containers:
          - name: mydb
            image: postgres
            env:
              - name: POSTGRESS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: password
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: myuser
              - name: POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: dbname
...
-> ls -l
-> chmod 700 -R secret.yaml
we can also add another level of security by encripitting the data if someone accidently opens no one can remember that
-> echo "myuser" | base64 =  bXl1c2VyIHVzZXIK
-> echo "password" | base64 =  amVldmFua29obGkgdXNlcgo=
-> echo "mydb" | base64  =  bXlkYiB1c2VyCg==
kubectl apply -f secret2.yaml
kubectl apply -f postgres-deployment.yaml
kubectl get all

